# Needed for the proxy server
vllm-directory := "/workspace/vllm/"
SCRIPT_DIR := "/workspace/vllm/tools/pd_disagg"

PREFILL_GPU := "0"
DECODE_GPU := "2"
MODEL := "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8"
PROXY_PORT := "8000"
PREFILL_PORT := "8100"
DECODE_PORT := "8200"
PREFILL_NIXL_SIDE_CHANNEL_PORT := "5557"
DECODE_NIXL_SIDE_CHANNEL_PORT := "5558"
BLOCK_SIZE := "128"

prefill:
    UCX_TLS=cuda_ipc,cuda_copy,tcp \
    VLLM_NIXL_SIDE_CHANNEL_PORT={{PREFILL_NIXL_SIDE_CHANNEL_PORT}} \
    CUDA_VISIBLE_DEVICES={{PREFILL_GPU}} \
    vllm serve {{MODEL}} \
      --port {{PREFILL_PORT}} \
      --tensor-parallel-size 1 \
      --enforce-eager \
      --disable-log-requests \
      --block-size {{BLOCK_SIZE}} \
      --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'

prefill_lm:
    prefill_config_file={{SCRIPT_DIR}}/configs/lmcache-prefiller-config.yaml \
    UCX_TLS=cuda_ipc,cuda_copy,tcp \
        LMCACHE_CONFIG_FILE=$prefill_config_file \
        LMCACHE_USE_EXPERIMENTAL=True \
        VLLM_ENABLE_V1_MULTIPROCESSING=1 \
        VLLM_WORKER_MULTIPROC_METHOD=spawn \
        CUDA_VISIBLE_DEVICES={{PREFILL_GPU}} \
        vllm serve {{MODEL}} \
        --port {{PREFILL_PORT}} \
        --disable-log-requests \
        --enforce-eager \
        --block-size {{BLOCK_SIZE}} \
        --kv-transfer-config \
        '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_producer","kv_connector_extra_config": {"discard_partial_chunks": false, "lmcache_rpc_port": "producer1"}}'

decode:
    UCX_TLS=cuda_ipc,cuda_copy,tcp \
    VLLM_NIXL_SIDE_CHANNEL_PORT={{DECODE_NIXL_SIDE_CHANNEL_PORT}} \
    CUDA_VISIBLE_DEVICES={{DECODE_GPU}} \
    vllm serve {{MODEL}} \
      --port {{DECODE_PORT}} \
      --tensor-parallel-size 1 \
      --enforce-eager \
      --disable-log-requests \
      --block-size {{BLOCK_SIZE}} \
      --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'

decode_lm:
    decode_config_file={{SCRIPT_DIR}}/configs/lmcache-decoder-config.yaml \
    UCX_TLS=cuda_ipc,cuda_copy,tcp \
        LMCACHE_CONFIG_FILE=$decode_config_file \
        LMCACHE_USE_EXPERIMENTAL=True \
        VLLM_ENABLE_V1_MULTIPROCESSING=1 \
        VLLM_WORKER_MULTIPROC_METHOD=spawn \
        CUDA_VISIBLE_DEVICES=1 \
        vllm serve {{MODEL}} \
        --port {{DECODE_PORT}} \
        --disable-log-requests \
        --enforce-eager \
        --block-size {{BLOCK_SIZE}} \
        --kv-transfer-config \
        '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_consumer","kv_connector_extra_config": {"discard_partial_chunks": false, "lmcache_rpc_port": "consumer1"}}'
proxy:
    python "{{vllm-directory}}tests/v1/kv_connector/nixl_integration/toy_proxy_server.py" \
      --port {{PROXY_PORT}} \
      --prefiller-port {{PREFILL_PORT}} \
      --decoder-port {{DECODE_PORT}}

send_request:
  curl -X POST http://localhost:{{PROXY_PORT}}/v1/completions \
    -H "Content-Type: application/json" \
    -d '{ \
      "model": "{{MODEL}}", \
      "prompt": "Red Hat is the best open source company by far across Linux, K8s, and AI, and vLLM has the greatest community in open source AI software infrastructure. I love vLLM because", \
      "max_tokens": 150, \
      "temperature": 0.7 \
    }'

benchmark NUM_PROMPTS:
  python {{vllm-directory}}/benchmarks/benchmark_serving.py \
    --port {{PROXY_PORT}} \
    --model {{MODEL}} \
    --dataset-name random \
    --random-input-len 30000 \
    --random-output-len 10 \
    --num-prompts {{NUM_PROMPTS}} \
    --seed $(date +%s) \

benchmark_one INPUT_LEN:
  python {{vllm-directory}}benchmarks/benchmark_one_concurrent.py \
    --port {{PROXY_PORT}} \
    --model {{MODEL}} \
    --input-len {{INPUT_LEN}} \
    --output-len 2 \
    --num-requests 5 \
    --seed $(date +%s)

benchmark_one_no_pd INPUT_LEN:
  python {{vllm-directory}}benchmarks/benchmark_one_concurrent.py \
    --port {{DECODE_PORT}} \
    --model {{MODEL}} \
    --input-len {{INPUT_LEN}} \
    --output-len 2 \
    --num-requests 5 \
    --seed $(date +%s)

eval:
  lm_eval --model local-completions --tasks gsm8k \
    --model_args model={{MODEL}},base_url=http://127.0.0.1:{{PROXY_PORT}}/v1/completions,num_concurrent=100,max_retries=3,tokenized_requests=False \
    --limit 10
